### ISSUE TITLE
Support for Python3

### ISSUE THREAD

**Issue by mldulaney** [xmpppy/xmpppy#24]
Just to let y'all know, I'm forking to work on python3 support, and will send a pull request when done.

**Comment by amotl** [comment]
Dear Mairi,

am I right to assume 1ef4aad5 will bring Python3 support to this code base already?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi there,

after integrating ea366609 by @lilmike (thanks!) and complementing it with 39909d6b and 9e116f54, I've just released version 0.6.0 on PyPI. This version essentially supports Python3 for - at least - a basic messaging example. Saying that, I will be happy to get reports about further Python3-compatibility issues in order to mitigate them.

With kind regards,
Andreas.

P.S.: Thanks also @jhdulaney! I decided to use the other commit for approaching Python3 compatibility as the reformatting changes of 1ef4aad made the diff too noisy to grok for me. However, the code formatting definitively needs some love, so we should throw [Black](https://pypi.org/project/black/) onto the code base at some time in the near future.

**Comment by gdt** [comment]
I am updating the xmpppy package for pkgsrc.org, and as part of that I tried with python 3.8.   The xsend.py example is broken, missing parens around print args.  With that fixed, there's a concat str/bytes issue.  I realize this isn't a useful bug report, just a data point that from an unfamiliar person's viewpoint, the package is not py3 ready.

**Comment by amotl** [comment]
Through recent improvements coming from #45, #54, #55, #58 and #59, I think Python 3 compatibility is reasonably mature now. Therefore, I am closing this issue.

**Comment by gdt** [comment]
I am surely not doing everything that is doable, but basic message sending works for me, and I concur with closing.   Basically, I think we've arrived at a situation where if there is a python3 bug, its just a bug, not a systemic failure where nothing works in 3.
